-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

-- CREATE TABLE: CATEGORY
CREATE TABLE category (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL
);

-- CREATE TABLE: PRODUCT
CREATE TABLE product (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  price DECIMAL NOT NULL,
  stock INTEGER NOT NULL DEFAULT(10),
  categoty_id INTEGER,
    FOREIGN KEY (category_id)
    REFERENCES category(id)
    ON DELETE SET NULL
);

-- CREATE TABLE: TAG
CREATE TABLE tag (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tag_name VARCHAR(255) NOT NULL
);

-- CREATE TABLE: PRODUCT_TAG
CREATE TABLE product_tag (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id INTEGER,
    FOREIGN KEY (product_id)
    REFERENCES product(id)
    ON DELETE SET NULL,
  tag_id INTEGER,
    FOREIGN KEY (tag_id)
    REFERENCES tag(id)
    ON DELETE SET NULL
);
